remove copy/paste errors from install-npm script

diff --git a/src/scripts/install-npm b/src/scripts/install-npm
--- a/src/scripts/install-npm
+++ b/src/scripts/install-npm
@@ -5,7 +5,7 @@ set -e -o pipefail
 if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
 
 # FUNCTIONS
-get_npm_NPM_VERSION () {
+get_npm_version() {
   if [[ $NPM_VERSION == latest ]]; then
     NPM_ORB_VERSION="$(npm view npm | sed -E 's|.*-||g' | grep latest | \
       perl -pe 's/.*: //g' | perl -pe "s/'|,//g")"
@@ -27,21 +27,21 @@ installation_check () {
   fi
 }
 
-get_npm_NPM_VERSION
-  installation_check
+get_npm_version
+installation_check
 
-  if [[ "${NPM_VERSION}" == latest ]]; then
-    $SUDO npm install -g npm@latest > /dev/null 2>&1 || \
-      npm install -g npm@latest > /dev/null 2>&1
-  else
-    $SUDO npm install -g "npm@$NPM_ORB_VERSION" > /dev/null 2>&1 || \
-      npm install -g "npm@$NPM_ORB_VERSION" > /dev/null 2>&1
-  fi
+if [[ $NPM_VERSION == latest ]]; then
+  $SUDO npm install -g npm@latest > /dev/null 2>&1 || \
+    npm install -g npm@latest > /dev/null 2>&1
+else
+  $SUDO npm install -g "npm@$NPM_ORB_VERSION" > /dev/null 2>&1 || \
+    npm install -g "npm@$NPM_ORB_VERSION" > /dev/null 2>&1
+fi
 
-  # test/verify NPM_VERSION
-  if npm -v | grep "$NPM_ORB_VERSION" > /dev/null 2>&1; then
-    echo "Success! NPM $(npm -v) has been installed to $(which npm)"
-  else
-    echo "Something went wrong; the specified NPM_VERSION of NPM could not be installed"
-    exit 1
-  fi
+# test/verify NPM_VERSION
+if npm -v | grep "$NPM_ORB_VERSION" > /dev/null 2>&1; then
+  echo "Success! NPM $(npm -v) has been installed to $(which npm)"
+else
+  echo "Something went wrong; the specified NPM_VERSION of NPM could not be installed"
+  exit 1
+fi
